language: cpp
dist: xenial

addons:
  apt:
    sources:
      - sourceline: "ppa:ubuntu-toolchain-r/test"
    packages:
      - gcc-8
      - g++-8

script:
  - export CC=gcc-8 && export CXX=g++-8 && cmake . && make
  - export CC=clang && export CXX=clang++ && cmake . && make
