language: cpp
dist: bionic
compiler:
  - gcc
  - clang
os:
  - linux
  - windows

addons:
  apt:
    packages:
      - gcc-8
      - g++-8

before_install:
  - if [[ "$TRAVIS_COMPILER" == "gcc" ]]; then export CC=gcc-8; export CXX=g++-8; fi

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .