on:
  push:
    tags:
      - 'v*'

name: Release

jobs:
  release:
    name: Upload
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Create build dir
        run: mkdir build
      - name: Build
        if: runner.os != 'Windows'
        run: |
          cd build
          cmake -G Ninja ..
          cmake --build . --config Release
      - name: Build on Windows or macOS
        if: runner.os == 'Windows'
        run: |
          cd build
          cmake ..
          cmake --build . --config Release
      - name: Rename macOS artifacts
        if: runner.os == 'macOS'
        working-directory: ./bin
        run: |
          mv von-neumann von-neumann-macos
      - name: Upload Linux asset
        if: runner.os == 'Linux'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./bin/von-neumann"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          allowUpdates: true
      - name: Upload Windows asset
        if: runner.os == 'Windows'
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          artifacts: "./bin/Release/von-neumann.exe"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          allowUpdates: true
      - name: Upload macOS asset
        if: runner.os == 'macOS'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./bin/von-neumann-macos"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          allowUpdates: true
